spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
app:
  api-base-domain: "api.shortener.scg.skku.ac.kr"
  api-base-url: "https://${app.api-base-domain}"
  slug-base-domain: "scg.sh"
  slug-base-url: "https://${app.slug-base-domain}"
  dashboard-url: "https://scg.sh/dashboard"
  allowed-origins:
    - "https://scg.sh"