spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
app:
  api-base-domain: "api.shortener.scg.skku.ac.kr"
  api-base-url: "https://${app.api-base-domain}"
  slug-base-domain: "app.shortener.scg.skku.ac.kr"
  slug-base-url: "https://${app.slug-base-domain}"
  dashboard-url: "https://app.shortener.scg.skku.ac.kr/dashboard"
  allowed-origins:
    - "https://app.shortener.scg.skku.ac.kr"